apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 3100
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer