apiVersion: v1
kind: Service
metadata:
  name: wordpress-frontend
  namespace: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
    tier: frontend