apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 3100
    protocol: TCP
    targetPort: 3100
    name: web
  selector:
    app: wordpress